{
  "uuid": "be5d629f-b981-4472-b448-bd1bf0e35cac",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "95d68a6d-a039-4a3b-a474-a72767a3756b"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1720574175609,
  "stop": 1720574179098
}