{
  "uuid": "080e2e29-c4bc-419e-963f-4a4d8a91bec8",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "07065fc0-effc-420f-a1aa-276cf6ccd2df"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1712644183801,
  "stop": 1712644188394
}