{
  "uuid": "df070d52-29cc-45f1-be22-a072fae8b2eb",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "734571c0-d193-4d94-b357-bbffdda80eec"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1706072347990,
  "stop": 1706072353291
}