{
  "uuid": "f71d6679-0498-4608-bdb8-1ac6e532e41c",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "3f239172-6bcc-4382-ac95-f145c0631b48"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1737565937471,
  "stop": 1737565953163
}