{
  "uuid": "629b4747-fa14-476b-9d98-bcc66450b651",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "c954942c-b4b1-4119-a71a-4acc11195ffc"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1706660738748,
  "stop": 1706660745149
}