{
  "uuid": "717aa5ed-716b-4208-b257-a265240b5f45-tr-0-1171",
  "historyId": "OdinUiTests.Tests.Library.TestSettingsValidationTests.Конструктор теста: можно добавить автора",
  "fullName": "OdinUiTests.Tests.Library.TestSettingsValidationTests.Конструктор теста: можно добавить автора",
  "labels": [
    {
      "name": "thread",
      "value": "ParallelWorker#3"
    },
    {
      "name": "host",
      "value": "ec4c06aaf65c"
    },
    {
      "name": "package",
      "value": "OdinUiTests.Tests.Library"
    },
    {
      "name": "testMethod",
      "value": "AddAuthorInTest"
    },
    {
      "name": "testClass",
      "value": "TestSettingsValidationTests"
    },
    {
      "name": "tag",
      "value": "Материал"
    },
    {
      "name": "tag",
      "value": "Дежурство"
    },
    {
      "name": "tag",
      "value": "Регресс"
    },
    {
      "name": "suite",
      "value": "Материал"
    },
    {
      "name": "subSuite",
      "value": "Конструктор теста"
    },
    {
      "name": "severity",
      "value": "critical"
    }
  ],
  "links": [],
  "name": "Конструктор теста: можно добавить автора",
  "status": "failed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false,
    "message": "System.AggregateException : One or more errors occurred. (Connection refused (test11.odin.study:443))\n  ----> System.Net.Http.HttpRequestException : Connection refused (test11.odin.study:443)\n  ----> System.Net.Sockets.SocketException : Connection refused",
    "trace": "   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\n   at OdinUiTests.Services.AccountService.GetAccessToken(UsersEnum user) in /azp/_work/3/s/Services/AccountService.cs:line 20\n   at OdinUiTests.Services.TestService.EditTest(String testId, Boolean isTestTrain, Int32[] authorIds) in /azp/_work/3/s/Services/TestService.cs:line 155\n   at OdinUiTests.Tests.Library.TestSettingsValidationTests.AddAuthorInTest() in /azp/_work/3/s/Tests/Library/TestCreateEditTests.cs:line 89\n--HttpRequestException\n   at RestSharp.RestClientExtensions.PostAsync(IRestClient client, RestRequest request, CancellationToken cancellationToken)\n--SocketException\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\n   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)"
  },
  "stage": "finished",
  "steps": [
    {
      "name": "Конструктор теста: можно добавить автора",
      "status": "failed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false,
        "message": "System.AggregateException : One or more errors occurred. (Connection refused (test11.odin.study:443))\n  ----> System.Net.Http.HttpRequestException : Connection refused (test11.odin.study:443)\n  ----> System.Net.Sockets.SocketException : Connection refused",
        "trace": "   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\n   at OdinUiTests.Services.AccountService.GetAccessToken(UsersEnum user) in /azp/_work/3/s/Services/AccountService.cs:line 20\n   at OdinUiTests.Services.TestService.EditTest(String testId, Boolean isTestTrain, Int32[] authorIds) in /azp/_work/3/s/Services/TestService.cs:line 155\n   at OdinUiTests.Tests.Library.TestSettingsValidationTests.AddAuthorInTest() in /azp/_work/3/s/Tests/Library/TestCreateEditTests.cs:line 89\n--HttpRequestException\n   at RestSharp.RestClientExtensions.PostAsync(IRestClient client, RestRequest request, CancellationToken cancellationToken)\n--SocketException\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\n   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)"
      },
      "stage": "finished",
      "steps": [],
      "attachments": [
        {
          "name": "AddAuthorInTest.jpg",
          "source": "70eb90bc694f4e8eba1cf311816d2fa8-attachment.jpg",
          "type": "image/jpeg"
        },
        {
          "name": "Console Output",
          "source": "9dfa080cfc874ae7a320767d19190847-attachment.txt",
          "type": "text/plain"
        }
      ],
      "parameters": [],
      "start": 1697085453091,
      "stop": 1697085453313
    }
  ],
  "attachments": [],
  "parameters": [],
  "start": 1697085453091,
  "stop": 1697085453313
}