{
  "uuid": "6c6159c9-20b7-4755-a908-d300fd9f06d8",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "6ae322cf-f64a-4804-b3ab-b07960b42d2c"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1759903135466,
  "stop": 1759903146667
}