{
  "uuid": "c4fe0dc8-db09-46db-8c1f-6eb6bc802e0b",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "734b3f5a-a5b6-426a-a94c-ec841ee31387"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1732025106502,
  "stop": 1732025130410
}