{
  "uuid": "411c186e-8bf6-467b-8b37-605c2ef46d2f",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "35cbdc7b-154a-4d83-aeed-3fc80fb1481d"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1715758173052,
  "stop": 1715758181009
}