{
  "uuid": "e664b315-5fed-4867-90b8-0f2e58e0595c",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "05bc5c33-8511-4669-a9d1-fa0db06c39f7"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1739341274633,
  "stop": 1739341289238
}