{
  "uuid": "a7857f48-a753-4188-b7db-76461eb204ee",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "9b73f520-a557-4e39-9db1-bc4c913a021d"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1757993932345,
  "stop": 1757993944143
}