{
  "uuid": "281515a2-fc40-4e3d-9731-c1c2dab300fd",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "af201a15-dae5-4b39-a6dd-08348452786a"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1706593086873,
  "stop": 1706593096035
}