{
  "uuid": "15237d3e-6de4-4858-8c4a-ed12c384d034",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "dc876423-7680-446a-8d04-9cee3a1512c6"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1721372492955,
  "stop": 1721372497893
}