{
  "uuid": "ad9be8d3-ea78-44fa-9edf-657e6b74fc5f",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "4bf5def1-cbb9-4d59-b37d-643c4ffe4a7b"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1727437786645,
  "stop": 1727437792981
}