{
  "uuid": "995ed55e-8b70-48ab-b638-ae3c8258f6ef",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "d6713d91-1752-4248-a85f-4eca086058d0"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1721715113305,
  "stop": 1721715117633
}