{
  "uuid": "b26ad40b-b5d6-4a56-adc8-da4ac821d7d7",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "a6595879-c828-47a4-ad7c-cc1ed0d799ef"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1747375926424,
  "stop": 1747375943235
}