{
  "uuid": "aeab94d6-bb49-439a-a21d-c15265eeaf49",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "ac1ef652-b384-425a-9c06-343376bcfaa1"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1741048821306,
  "stop": 1741048835394
}