{
  "uuid": "b5886ada-887f-4ce9-a6df-44624cdb03d8",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "ef3b1a2e-dd76-4d19-926e-c9818eae68ea"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1734576149867,
  "stop": 1734576157927
}