{
  "uuid": "502dfa68-7439-4cda-993c-5324e1edc747",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "d09ab6b2-34f2-4620-9d19-8e99398a8afe"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1727091920331,
  "stop": 1727091926231
}