{
  "uuid": "2d913366-ae89-441c-bc1b-9ceb368b7807",
  "name": "OdinUiTests.Tests.Activity.TaskWithSolutionStudentTests.Появление ошибки при удалении решения",
  "children": [
    "aa8cb8eb-d4e6-4211-bf33-8a061da5e6d6"
  ],
  "befores": [],
  "afters": [],
  "links": [],
  "start": 1736950576847,
  "stop": 1736950587068
}