{
  "uuid": "a5e06e48-4e99-4e1a-be4c-d2594cdc31a8-tr-0-1111",
  "historyId": "OdinUiTests.Tests.Program.ProgramInfoPageTests.Страница обр программы: При восстановлении из архива обр программы появляется модалка подтверждения действия",
  "fullName": "OdinUiTests.Tests.Program.ProgramInfoPageTests.Страница обр программы: При восстановлении из архива обр программы появляется модалка подтверждения действия",
  "labels": [
    {
      "name": "thread",
      "value": "ParallelWorker#2"
    },
    {
      "name": "host",
      "value": "ec4c06aaf65c"
    },
    {
      "name": "package",
      "value": "OdinUiTests.Tests.Program"
    },
    {
      "name": "testMethod",
      "value": "CheckWindowsRestoreArchiveEducationProgram"
    },
    {
      "name": "testClass",
      "value": "ProgramInfoPageTests"
    },
    {
      "name": "tag",
      "value": "Программа"
    },
    {
      "name": "tag",
      "value": "Дежурство"
    },
    {
      "name": "tag",
      "value": "Регресс"
    },
    {
      "name": "suite",
      "value": "Программа"
    },
    {
      "name": "severity",
      "value": "normal"
    }
  ],
  "links": [],
  "name": "Страница обр программы: При восстановлении из архива обр программы появляется модалка подтверждения действия",
  "status": "failed",
  "statusDetails": {
    "known": false,
    "muted": false,
    "flaky": false,
    "message": "System.AggregateException : One or more errors occurred. (Connection refused (test11.odin.study:443))\n  ----> System.Net.Http.HttpRequestException : Connection refused (test11.odin.study:443)\n  ----> System.Net.Sockets.SocketException : Connection refused",
    "trace": "   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\n   at OdinUiTests.Services.ProgramService.EditArchivingOfProgram(String programId, Boolean isArchive) in /azp/_work/3/s/Services/ProgramService.cs:line 117\n   at OdinUiTests.Tests.Program.ProgramInfoPageTests.CheckWindowsRestoreArchiveEducationProgram() in /azp/_work/3/s/Tests/Program/ProgramCommonTests.cs:line 157\n--HttpRequestException\n   at RestSharp.RestClientExtensions.PostAsync(IRestClient client, RestRequest request, CancellationToken cancellationToken)\n--SocketException\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\n   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)"
  },
  "stage": "finished",
  "steps": [
    {
      "name": "Страница обр программы: При восстановлении из архива обр программы появляется модалка подтверждения действия",
      "status": "failed",
      "statusDetails": {
        "known": false,
        "muted": false,
        "flaky": false,
        "message": "System.AggregateException : One or more errors occurred. (Connection refused (test11.odin.study:443))\n  ----> System.Net.Http.HttpRequestException : Connection refused (test11.odin.study:443)\n  ----> System.Net.Sockets.SocketException : Connection refused",
        "trace": "   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)\n   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)\n   at OdinUiTests.Services.ProgramService.EditArchivingOfProgram(String programId, Boolean isArchive) in /azp/_work/3/s/Services/ProgramService.cs:line 117\n   at OdinUiTests.Tests.Program.ProgramInfoPageTests.CheckWindowsRestoreArchiveEducationProgram() in /azp/_work/3/s/Tests/Program/ProgramCommonTests.cs:line 157\n--HttpRequestException\n   at RestSharp.RestClientExtensions.PostAsync(IRestClient client, RestRequest request, CancellationToken cancellationToken)\n--SocketException\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)\n   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)\n   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)\n   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)"
      },
      "stage": "finished",
      "steps": [],
      "attachments": [
        {
          "name": "CheckWindowsRestoreArchiveEducationProgram.jpg",
          "source": "e8ac223524cf4fadae7f14bc27b7c4cd-attachment.jpg",
          "type": "image/jpeg"
        },
        {
          "name": "Console Output",
          "source": "8b6e72bda3f94712be47fe13f46bb83c-attachment.txt",
          "type": "text/plain"
        }
      ],
      "parameters": [],
      "start": 1697085458507,
      "stop": 1697085458747
    }
  ],
  "attachments": [],
  "parameters": [],
  "start": 1697085458507,
  "stop": 1697085458747
}